### PR TITLE
Tags and header

### PR DESCRIPTION
**Pull request by arpitux**
Fixed the overflowing tags and [+8] button,

Changed header structure to reduce one extra click to bring search box.

Added a Price filter UI. (In progress)

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Can you remove the pricing slider until it is ready?  When I merge this change it will go live immediately and I don't want users struggling to figure out how the slider works if it isn't fully implemented yet.

**Comment by MicahZoltu** [comment]
Same with the reset button, can you hide it for now since it doesn't appear to work at the moment (or make it work) so I can get this merged?

**Comment by MicahZoltu** [comment]
And can you also change the title to something like "Filter by Price" until the button updates with the real values.

**Comment by arpitux** [comment]
I have commented out the complete Price filter as those predefined ranges are also not completely done.

**Pull request merged**
